In [1]:
import pandas as pd

In [2]:
people = {
    "first_name": ["Mosh", "Kim", "Ted"],
    "last_name": ["Hamedani", "Black", "Beneky"],
    "email": ["mosh@hamedan.ir", "kblack@google.com", "tbnk@lg.co"]
}

In [3]:
df = pd.DataFrame(people)

In [4]:
df

  first_name last_name              email
0       Mosh  Hamedani    mosh@hamedan.ir
1        Kim     Black  kblack@google.com
2        Ted    Beneky         tbnk@lg.co

In [5]:
df.set_index('email')

                  first_name last_name
email
mosh@hamedan.ir         Mosh  Hamedani
kblack@google.com        Kim     Black
tbnk@lg.co               Ted    Beneky

In [6]:
df

  first_name last_name              email
0       Mosh  Hamedani    mosh@hamedan.ir
1        Kim     Black  kblack@google.com
2        Ted    Beneky         tbnk@lg.co

In [7]:
df.set_index('email', inplace=True)

In [8]:
df

                  first_name last_name
email
mosh@hamedan.ir         Mosh  Hamedani
kblack@google.com        Kim     Black
tbnk@lg.co               Ted    Beneky

In [9]:
df.index

Index(['mosh@hamedan.ir', 'kblack@google.com', 'tbnk@lg.co'], dtype='object', name='email')

In [11]:
df.loc['mosh@hamedan.ir', ['first_name', 'last_name']]

first_name        Mosh
last_name     Hamedani
Name: mosh@hamedan.ir, dtype: object

In [12]:
df.reset_index(inplace=True)

In [13]:
df

               email first_name last_name
0    mosh@hamedan.ir       Mosh  Hamedani
1  kblack@google.com        Kim     Black
2         tbnk@lg.co        Ted    Beneky

You can also set index when creating a dataframe.

In [14]:
df = pd.read_csv("survey_results_public.csv", index_col="Respondent")

In [15]:
df

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10039,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,NaN,25.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
10040,I am a developer by profession,No,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,28.0,Man,No,Straight / Heterosexual,South Asian,Yes,Appropriate in length,Easy
10041,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,United States,No,Some college/university study without earning ...,Fine arts or performing arts (ex. graphic desi...,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Cour...,28.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
10042,I am a developer by profession,No,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Colombia,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,NaN,Tech articles written by other developers;Indu...,39.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina,Yes,Appropriate in length,Neither easy nor difficult
10043,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Canada,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Cour...,25.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,Yes,Appropriate in length,Neither easy nor difficult

In [17]:
schema_df = pd.read_csv("survey_results_schema.csv", index_col="Column")

In [18]:
schema_df

                                                   QuestionText
Column
Respondent    Randomized respondent ID number (not in order ...
MainBranch    Which of the following options best describes ...
Hobbyist                                Do you code as a hobby?
OpenSourcer         How often do you contribute to open source?
OpenSource    How do you feel about the quality of open sour...
...                                                         ...
Sexuality     Which of the following do you currently identi...
Ethnicity     Which of the following do you identify as? Ple...
Dependents    Do you have any dependents (e.g., children, el...
SurveyLength  How do you feel about the length of the survey...
SurveyEase    How easy or difficult was this survey to compl...

[85 rows x 1 columns]

In [19]:
schema_df.loc['MgrIdiot', 'QuestionText']

'How confident are you that your manager knows what they’re doing?'

In [21]:
schema_df.sort_index(inplace=True)

In [22]:
schema_df

                                                    QuestionText
Column
Age            What is your age (in years)? If you prefer not...
Age1stCode     At what age did you write your first line of c...
BetterLife     Do you think people born today will have a bet...
BlockchainIs   Blockchain / cryptocurrency technology is prim...
BlockchainOrg  How is your organization thinking about or imp...
...                                                          ...
WorkPlan                 How structured or planned is your work?
WorkRemote                       How often do you work remotely?
WorkWeekHrs     On average, how many hours per week do you work?
YearsCode      Including any education, how many years have y...
YearsCodePro   How many years have you coded professionally (...

[85 rows x 1 columns]